/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Collections.ObjectModel;
using OpenHolidaysApi.Client;
using OpenHolidaysApi.Model;
using RestSharp;

namespace OpenHolidaysApi.Api;

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public interface IStatisticsApi : IApiAccessor
{
    #region Synchronous Operations

    /// <summary>
    ///     Returns statistical data about public holidays for a given country.
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>List&lt;StatisticsResponse&gt;</returns>
    List<StatisticsResponse> StatisticsPublicHolidaysGet(string countryIsoCode, string subdivisionCode = null);

    /// <summary>
    ///     Returns statistical data about public holidays for a given country.
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>ApiResponse of List&lt;StatisticsResponse&gt;</returns>
    ApiResponse<List<StatisticsResponse>> StatisticsPublicHolidaysGetWithHttpInfo(string countryIsoCode,
        string subdivisionCode = null);

    /// <summary>
    ///     Returns statistical data about school holidays for a given country
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>List&lt;StatisticsResponse&gt;</returns>
    List<StatisticsResponse> StatisticsSchoolHolidaysGet(string countryIsoCode, string subdivisionCode = null);

    /// <summary>
    ///     Returns statistical data about school holidays for a given country
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>ApiResponse of List&lt;StatisticsResponse&gt;</returns>
    ApiResponse<List<StatisticsResponse>> StatisticsSchoolHolidaysGetWithHttpInfo(string countryIsoCode,
        string subdivisionCode = null);

    #endregion Synchronous Operations

    #region Asynchronous Operations

    /// <summary>
    ///     Returns statistical data about public holidays for a given country.
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>Task of List&lt;StatisticsResponse&gt;</returns>
    Task<List<StatisticsResponse>> StatisticsPublicHolidaysGetAsync(string countryIsoCode,
        string subdivisionCode = null);

    /// <summary>
    ///     Returns statistical data about public holidays for a given country.
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>Task of ApiResponse (List&lt;StatisticsResponse&gt;)</returns>
    Task<ApiResponse<List<StatisticsResponse>>> StatisticsPublicHolidaysGetAsyncWithHttpInfo(string countryIsoCode,
        string subdivisionCode = null);

    /// <summary>
    ///     Returns statistical data about school holidays for a given country
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>Task of List&lt;StatisticsResponse&gt;</returns>
    Task<List<StatisticsResponse>> StatisticsSchoolHolidaysGetAsync(string countryIsoCode,
        string subdivisionCode = null);

    /// <summary>
    ///     Returns statistical data about school holidays for a given country
    /// </summary>
    /// <remarks>
    /// </remarks>
    /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>Task of ApiResponse (List&lt;StatisticsResponse&gt;)</returns>
    Task<ApiResponse<List<StatisticsResponse>>> StatisticsSchoolHolidaysGetAsyncWithHttpInfo(string countryIsoCode,
        string subdivisionCode = null);

    #endregion Asynchronous Operations
}

/// <summary>
///     Represents a collection of functions to interact with the API endpoints
/// </summary>
public class StatisticsApi : IStatisticsApi
{
    private ExceptionFactory _exceptionFactory = (name, response) => null;

    /// <summary>
    ///     Initializes a new instance of the <see cref="StatisticsApi" /> class.
    /// </summary>
    /// <returns></returns>
    public StatisticsApi(string basePath)
    {
        Configuration = new Configuration { BasePath = basePath };

        ExceptionFactory = Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="StatisticsApi" /> class
    /// </summary>
    /// <returns></returns>
    public StatisticsApi()
    {
        Configuration = Configuration.Default;

        ExceptionFactory = Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     Initializes a new instance of the <see cref="StatisticsApi" /> class
    ///     using Configuration object
    /// </summary>
    /// <param name="configuration">An instance of Configuration</param>
    /// <returns></returns>
    public StatisticsApi(Configuration configuration = null)
    {
        if (configuration == null) // use the default one in Configuration
            Configuration = Configuration.Default;
        else
            Configuration = configuration;

        ExceptionFactory = Configuration.DefaultExceptionFactory;
    }

    /// <summary>
    ///     Gets the base path of the API client.
    /// </summary>
    /// <value>The base path</value>
    public string GetBasePath()
    {
        return Configuration.ApiClient.RestClient.Options.BaseUrl.ToString();
    }

    /// <summary>
    ///     Gets or sets the configuration object
    /// </summary>
    /// <value>An instance of the Configuration</value>
    public Configuration Configuration { get; set; }

    /// <summary>
    ///     Provides a factory method hook for the creation of exceptions.
    /// </summary>
    public ExceptionFactory ExceptionFactory
    {
        get
        {
            if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
            return _exceptionFactory;
        }
        set => _exceptionFactory = value;
    }

    /// <summary>
    ///     Returns statistical data about public holidays for a given country.
    /// </summary>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>List&lt;StatisticsResponse&gt;</returns>
    public List<StatisticsResponse> StatisticsPublicHolidaysGet(string countryIsoCode, string subdivisionCode = null)
    {
        ApiResponse<List<StatisticsResponse>> localVarResponse =
            StatisticsPublicHolidaysGetWithHttpInfo(countryIsoCode, subdivisionCode);
        return localVarResponse.Data;
    }

    /// <summary>
    ///     Returns statistical data about public holidays for a given country.
    /// </summary>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>ApiResponse of List&lt;StatisticsResponse&gt;</returns>
    public ApiResponse<List<StatisticsResponse>> StatisticsPublicHolidaysGetWithHttpInfo(string countryIsoCode,
        string subdivisionCode = null)
    {
        // verify the required parameter 'countryIsoCode' is set
        if (countryIsoCode == null)
            throw new ApiException(400,
                "Missing required parameter 'countryIsoCode' when calling StatisticsApi->StatisticsPublicHolidaysGet");

        var localVarPath = "/Statistics/PublicHolidays";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[]
        {
        };
        var localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new[]
        {
            "application/json",
            "text/json",
            "text/plain",
            "application/problem+json"
        };
        var localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (countryIsoCode != null)
            localVarQueryParams.AddRange(
                Configuration.ApiClient.ParameterToKeyValuePairs("", "countryIsoCode",
                    countryIsoCode)); // query parameter
        if (subdivisionCode != null)
            localVarQueryParams.AddRange(
                Configuration.ApiClient.ParameterToKeyValuePairs("", "subdivisionCode",
                    subdivisionCode)); // query parameter

        // make the HTTP request
        var localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
            localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        var localVarStatusCode = (int)localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            var exception = ExceptionFactory("StatisticsPublicHolidaysGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<List<StatisticsResponse>>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (List<StatisticsResponse>)Configuration.ApiClient.Deserialize(localVarResponse,
                typeof(List<StatisticsResponse>)));
    }

    /// <summary>
    ///     Returns statistical data about public holidays for a given country.
    /// </summary>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>Task of List&lt;StatisticsResponse&gt;</returns>
    public async Task<List<StatisticsResponse>> StatisticsPublicHolidaysGetAsync(string countryIsoCode,
        string subdivisionCode = null)
    {
        ApiResponse<List<StatisticsResponse>> localVarResponse =
            await StatisticsPublicHolidaysGetAsyncWithHttpInfo(countryIsoCode, subdivisionCode);
        return localVarResponse.Data;
    }

    /// <summary>
    ///     Returns statistical data about public holidays for a given country.
    /// </summary>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>Task of ApiResponse (List&lt;StatisticsResponse&gt;)</returns>
    public async Task<ApiResponse<List<StatisticsResponse>>> StatisticsPublicHolidaysGetAsyncWithHttpInfo(
        string countryIsoCode, string subdivisionCode = null)
    {
        // verify the required parameter 'countryIsoCode' is set
        if (countryIsoCode == null)
            throw new ApiException(400,
                "Missing required parameter 'countryIsoCode' when calling StatisticsApi->StatisticsPublicHolidaysGet");

        var localVarPath = "/Statistics/PublicHolidays";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[]
        {
        };
        var localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new[]
        {
            "application/json",
            "text/json",
            "text/plain",
            "application/problem+json"
        };
        var localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (countryIsoCode != null)
            localVarQueryParams.AddRange(
                Configuration.ApiClient.ParameterToKeyValuePairs("", "countryIsoCode",
                    countryIsoCode)); // query parameter
        if (subdivisionCode != null)
            localVarQueryParams.AddRange(
                Configuration.ApiClient.ParameterToKeyValuePairs("", "subdivisionCode",
                    subdivisionCode)); // query parameter

        // make the HTTP request
        var localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
            localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        var localVarStatusCode = (int)localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            var exception = ExceptionFactory("StatisticsPublicHolidaysGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<List<StatisticsResponse>>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (List<StatisticsResponse>)Configuration.ApiClient.Deserialize(localVarResponse,
                typeof(List<StatisticsResponse>)));
    }

    /// <summary>
    ///     Returns statistical data about school holidays for a given country
    /// </summary>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>List&lt;StatisticsResponse&gt;</returns>
    public List<StatisticsResponse> StatisticsSchoolHolidaysGet(string countryIsoCode, string subdivisionCode = null)
    {
        ApiResponse<List<StatisticsResponse>> localVarResponse =
            StatisticsSchoolHolidaysGetWithHttpInfo(countryIsoCode, subdivisionCode);
        return localVarResponse.Data;
    }

    /// <summary>
    ///     Returns statistical data about school holidays for a given country
    /// </summary>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>ApiResponse of List&lt;StatisticsResponse&gt;</returns>
    public ApiResponse<List<StatisticsResponse>> StatisticsSchoolHolidaysGetWithHttpInfo(string countryIsoCode,
        string subdivisionCode = null)
    {
        // verify the required parameter 'countryIsoCode' is set
        if (countryIsoCode == null)
            throw new ApiException(400,
                "Missing required parameter 'countryIsoCode' when calling StatisticsApi->StatisticsSchoolHolidaysGet");

        var localVarPath = "/Statistics/SchoolHolidays";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[]
        {
        };
        var localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new[]
        {
            "application/json",
            "text/json",
            "text/plain",
            "application/problem+json"
        };
        var localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (countryIsoCode != null)
            localVarQueryParams.AddRange(
                Configuration.ApiClient.ParameterToKeyValuePairs("", "countryIsoCode",
                    countryIsoCode)); // query parameter
        if (subdivisionCode != null)
            localVarQueryParams.AddRange(
                Configuration.ApiClient.ParameterToKeyValuePairs("", "subdivisionCode",
                    subdivisionCode)); // query parameter

        // make the HTTP request
        var localVarResponse = (RestResponse)Configuration.ApiClient.CallApi(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
            localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        var localVarStatusCode = (int)localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            var exception = ExceptionFactory("StatisticsSchoolHolidaysGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<List<StatisticsResponse>>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (List<StatisticsResponse>)Configuration.ApiClient.Deserialize(localVarResponse,
                typeof(List<StatisticsResponse>)));
    }

    /// <summary>
    ///     Returns statistical data about school holidays for a given country
    /// </summary>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>Task of List&lt;StatisticsResponse&gt;</returns>
    public async Task<List<StatisticsResponse>> StatisticsSchoolHolidaysGetAsync(string countryIsoCode,
        string subdivisionCode = null)
    {
        ApiResponse<List<StatisticsResponse>> localVarResponse =
            await StatisticsSchoolHolidaysGetAsyncWithHttpInfo(countryIsoCode, subdivisionCode);
        return localVarResponse.Data;
    }

    /// <summary>
    ///     Returns statistical data about school holidays for a given country
    /// </summary>
    /// <exception cref="ApiException">Thrown when fails to make API call</exception>
    /// <param name="countryIsoCode">ISO 3166-1 code of the country</param>
    /// <param name="subdivisionCode">Code of the subdivision or empty (optional)</param>
    /// <returns>Task of ApiResponse (List&lt;StatisticsResponse&gt;)</returns>
    public async Task<ApiResponse<List<StatisticsResponse>>> StatisticsSchoolHolidaysGetAsyncWithHttpInfo(
        string countryIsoCode, string subdivisionCode = null)
    {
        // verify the required parameter 'countryIsoCode' is set
        if (countryIsoCode == null)
            throw new ApiException(400,
                "Missing required parameter 'countryIsoCode' when calling StatisticsApi->StatisticsSchoolHolidaysGet");

        var localVarPath = "/Statistics/SchoolHolidays";
        var localVarPathParams = new Dictionary<string, string>();
        var localVarQueryParams = new List<KeyValuePair<string, string>>();
        var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
        var localVarFormParams = new Dictionary<string, string>();
        var localVarFileParams = new Dictionary<string, FileParameter>();
        object localVarPostBody = null;

        // to determine the Content-Type header
        string[] localVarHttpContentTypes = new string[]
        {
        };
        var localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

        // to determine the Accept header
        string[] localVarHttpHeaderAccepts = new[]
        {
            "application/json",
            "text/json",
            "text/plain",
            "application/problem+json"
        };
        var localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
        if (localVarHttpHeaderAccept != null)
            localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

        if (countryIsoCode != null)
            localVarQueryParams.AddRange(
                Configuration.ApiClient.ParameterToKeyValuePairs("", "countryIsoCode",
                    countryIsoCode)); // query parameter
        if (subdivisionCode != null)
            localVarQueryParams.AddRange(
                Configuration.ApiClient.ParameterToKeyValuePairs("", "subdivisionCode",
                    subdivisionCode)); // query parameter

        // make the HTTP request
        var localVarResponse = (RestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
            Method.Get, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams,
            localVarFileParams,
            localVarPathParams, localVarHttpContentType);

        var localVarStatusCode = (int)localVarResponse.StatusCode;

        if (ExceptionFactory != null)
        {
            var exception = ExceptionFactory("StatisticsSchoolHolidaysGet", localVarResponse);
            if (exception != null) throw exception;
        }

        return new ApiResponse<List<StatisticsResponse>>(localVarStatusCode,
            localVarResponse.Headers.ToDictionary(x => x.Name, x => string.Join(",", x.Value)),
            (List<StatisticsResponse>)Configuration.ApiClient.Deserialize(localVarResponse,
                typeof(List<StatisticsResponse>)));
    }

    /// <summary>
    ///     Sets the base path of the API client.
    /// </summary>
    /// <value>The base path</value>
    [Obsolete(
        "SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
    public void SetBasePath(string basePath)
    {
        // do nothing
    }

    /// <summary>
    ///     Gets the default header.
    /// </summary>
    /// <returns>Dictionary of HTTP header</returns>
    [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
    public IDictionary<string, string> DefaultHeader()
    {
        return new ReadOnlyDictionary<string, string>(Configuration.DefaultHeader);
    }

    /// <summary>
    ///     Add default header.
    /// </summary>
    /// <param name="key">Header field name.</param>
    /// <param name="value">Header field value.</param>
    /// <returns></returns>
    [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
    public void AddDefaultHeader(string key, string value)
    {
        Configuration.AddDefaultHeader(key, value);
    }
}