/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenHolidaysApi.Model;

/// <summary>
///     Representation of a country reference
/// </summary>
[DataContract]
public class CountryReference : IEquatable<CountryReference>, IValidatableObject
{
    /// <summary>
    ///     Initializes a new instance of the <see cref="CountryReference" /> class.
    /// </summary>
    /// <param name="isoCode">Country ISO code (required).</param>
    public CountryReference(string isoCode = default)
    {
        // to ensure "isoCode" is required (not null)

        IsoCode = isoCode ??
                  throw new InvalidDataException(
                      "isoCode is a required property for CountryReference and cannot be null");
    }

    /// <summary>
    ///     Country ISO code
    /// </summary>
    /// <value>Country ISO code</value>
    [DataMember(Name = "isoCode", EmitDefaultValue = false)]
    public string IsoCode { get; set; }

    /// <summary>
    ///     Returns true if CountryReference instances are equal
    /// </summary>
    /// <param name="input">Instance of CountryReference to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(CountryReference input)
    {
        if (input == null)
            return false;

        return
            IsoCode == input.IsoCode ||
            (IsoCode != null &&
             IsoCode.Equals(input.IsoCode));
    }

    /// <summary>
    ///     To validate all properties of the instance
    /// </summary>
    /// <param name="validationContext">Validation context</param>
    /// <returns>Validation Result</returns>
    IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
    {
        yield break;
    }

    /// <summary>
    ///     Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class CountryReference {\n");
        sb.Append("  IsoCode: ").Append(IsoCode).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    ///     Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public virtual string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    ///     Returns true if objects are equal
    /// </summary>
    /// <param name="input">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object input)
    {
        return Equals(input as CountryReference);
    }

    /// <summary>
    ///     Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            if (IsoCode != null)
                hashCode = hashCode * 59 + IsoCode.GetHashCode();
            return hashCode;
        }
    }
}