/* 
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenHolidaysApi.Model
{
    /// <summary>
    /// Representation of a holiday group reference
    /// </summary>
    [DataContract]
        public partial class GroupReference :  IEquatable<GroupReference>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GroupReference" /> class.
        /// </summary>
        /// <param name="code">Group code (required).</param>
        /// <param name="shortName">Short name for display (required).</param>
        public GroupReference(string code = default(string), string shortName = default(string))
        {
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new InvalidDataException("code is a required property for GroupReference and cannot be null");
            }
            else
            {
                this.Code = code;
            }
            // to ensure "shortName" is required (not null)
            if (shortName == null)
            {
                throw new InvalidDataException("shortName is a required property for GroupReference and cannot be null");
            }
            else
            {
                this.ShortName = shortName;
            }
        }
        
        /// <summary>
        /// Group code
        /// </summary>
        /// <value>Group code</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// Short name for display
        /// </summary>
        /// <value>Short name for display</value>
        [DataMember(Name="shortName", EmitDefaultValue=false)]
        public string ShortName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GroupReference {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  ShortName: ").Append(ShortName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GroupReference);
        }

        /// <summary>
        /// Returns true if GroupReference instances are equal
        /// </summary>
        /// <param name="input">Instance of GroupReference to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GroupReference input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.ShortName == input.ShortName ||
                    (this.ShortName != null &&
                    this.ShortName.Equals(input.ShortName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.ShortName != null)
                    hashCode = hashCode * 59 + this.ShortName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
