/* 
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenHolidaysApi.Model
{
    /// <summary>
    /// Representation of a holiday zone
    /// </summary>
    [DataContract]
        public partial class GroupResponse :  IEquatable<GroupResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GroupResponse" /> class.
        /// </summary>
        /// <param name="category">Localized categories of the group (required).</param>
        /// <param name="children">Child groups.</param>
        /// <param name="code">Group code (required).</param>
        /// <param name="comment">Localized comments of the group (required).</param>
        /// <param name="name">Localized names of the group (required).</param>
        /// <param name="shortName">Short name for display (required).</param>
        /// <param name="subdivisions">List of subdivision references.</param>
        public GroupResponse(List<LocalizedText> category = default(List<LocalizedText>), List<GroupResponse> children = default(List<GroupResponse>), string code = default(string), List<LocalizedText> comment = default(List<LocalizedText>), List<LocalizedText> name = default(List<LocalizedText>), string shortName = default(string), List<SubdivisionReference> subdivisions = default(List<SubdivisionReference>))
        {
            // to ensure "category" is required (not null)
            if (category == null)
            {
                throw new InvalidDataException("category is a required property for GroupResponse and cannot be null");
            }
            else
            {
                this.Category = category;
            }
            // to ensure "code" is required (not null)
            if (code == null)
            {
                throw new InvalidDataException("code is a required property for GroupResponse and cannot be null");
            }
            else
            {
                this.Code = code;
            }
            // to ensure "comment" is required (not null)
            // if (comment == null)
            // {
            //    throw new InvalidDataException("comment is a required property for GroupResponse and cannot be null");
            // }
            // else
            // {
                this.Comment = comment;
            // }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for GroupResponse and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "shortName" is required (not null)
            if (shortName == null)
            {
                throw new InvalidDataException("shortName is a required property for GroupResponse and cannot be null");
            }
            else
            {
                this.ShortName = shortName;
            }
            this.Children = children;
            this.Subdivisions = subdivisions;
        }
        
        /// <summary>
        /// Localized categories of the group
        /// </summary>
        /// <value>Localized categories of the group</value>
        [DataMember(Name="category", EmitDefaultValue=false)]
        public List<LocalizedText> Category { get; set; }

        /// <summary>
        /// Child groups
        /// </summary>
        /// <value>Child groups</value>
        [DataMember(Name="children", EmitDefaultValue=false)]
        public List<GroupResponse> Children { get; set; }

        /// <summary>
        /// Group code
        /// </summary>
        /// <value>Group code</value>
        [DataMember(Name="code", EmitDefaultValue=false)]
        public string Code { get; set; }

        /// <summary>
        /// Localized comments of the group
        /// </summary>
        /// <value>Localized comments of the group</value>
        [DataMember(Name="comment", EmitDefaultValue=false)]
        public List<LocalizedText> Comment { get; set; }

        /// <summary>
        /// Localized names of the group
        /// </summary>
        /// <value>Localized names of the group</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public List<LocalizedText> Name { get; set; }

        /// <summary>
        /// Short name for display
        /// </summary>
        /// <value>Short name for display</value>
        [DataMember(Name="shortName", EmitDefaultValue=false)]
        public string ShortName { get; set; }

        /// <summary>
        /// List of subdivision references
        /// </summary>
        /// <value>List of subdivision references</value>
        [DataMember(Name="subdivisions", EmitDefaultValue=false)]
        public List<SubdivisionReference> Subdivisions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GroupResponse {\n");
            sb.Append("  Category: ").Append(Category).Append("\n");
            sb.Append("  Children: ").Append(Children).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ShortName: ").Append(ShortName).Append("\n");
            sb.Append("  Subdivisions: ").Append(Subdivisions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GroupResponse);
        }

        /// <summary>
        /// Returns true if GroupResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GroupResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GroupResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Category == input.Category ||
                    this.Category != null &&
                    input.Category != null &&
                    this.Category.SequenceEqual(input.Category)
                ) && 
                (
                    this.Children == input.Children ||
                    this.Children != null &&
                    input.Children != null &&
                    this.Children.SequenceEqual(input.Children)
                ) && 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.Comment == input.Comment ||
                    this.Comment != null &&
                    input.Comment != null &&
                    this.Comment.SequenceEqual(input.Comment)
                ) && 
                (
                    this.Name == input.Name ||
                    this.Name != null &&
                    input.Name != null &&
                    this.Name.SequenceEqual(input.Name)
                ) && 
                (
                    this.ShortName == input.ShortName ||
                    (this.ShortName != null &&
                    this.ShortName.Equals(input.ShortName))
                ) && 
                (
                    this.Subdivisions == input.Subdivisions ||
                    this.Subdivisions != null &&
                    input.Subdivisions != null &&
                    this.Subdivisions.SequenceEqual(input.Subdivisions)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Category != null)
                    hashCode = hashCode * 59 + this.Category.GetHashCode();
                if (this.Children != null)
                    hashCode = hashCode * 59 + this.Children.GetHashCode();
                if (this.Code != null)
                    hashCode = hashCode * 59 + this.Code.GetHashCode();
                if (this.Comment != null)
                    hashCode = hashCode * 59 + this.Comment.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.ShortName != null)
                    hashCode = hashCode * 59 + this.ShortName.GetHashCode();
                if (this.Subdivisions != null)
                    hashCode = hashCode * 59 + this.Subdivisions.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
