/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace OpenHolidaysApi.Model;

/// <summary>
///     Type of holiday
/// </summary>
/// <value>Type of holiday</value>
[JsonConverter(typeof(StringEnumConverter))]
public enum HolidayType
{
    /// <summary>
    ///     Enum Public for value: Public
    /// </summary>
    [EnumMember(Value = "Public")] Public = 1,

    /// <summary>
    ///     Enum Bank for value: Bank
    /// </summary>
    [EnumMember(Value = "Bank")] Bank = 2,

    /// <summary>
    ///     Enum Optional for value: Optional
    /// </summary>
    [EnumMember(Value = "Optional")] Optional = 3,

    /// <summary>
    ///     Enum School for value: School
    /// </summary>
    [EnumMember(Value = "School")] School = 4,

    /// <summary>
    ///     Enum BackToSchool for value: BackToSchool
    /// </summary>
    [EnumMember(Value = "BackToSchool")] BackToSchool = 5,

    /// <summary>
    ///     Enum EndOfLessons for value: EndOfLessons
    /// </summary>
    [EnumMember(Value = "EndOfLessons")] EndOfLessons = 6
}