/* 
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenHolidaysApi.Model
{
    /// <summary>
    /// Representation of a holiday by date
    /// </summary>
    [DataContract]
        public partial class HolidayByDateResponse :  IEquatable<HolidayByDateResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HolidayByDateResponse" /> class.
        /// </summary>
        /// <param name="comment">Additional localized comments.</param>
        /// <param name="country">country (required).</param>
        /// <param name="groups">List of group references.</param>
        /// <param name="id">Unique holiday id (required).</param>
        /// <param name="name">Localized names of the holiday (required).</param>
        /// <param name="nationwide">Is the holiday nationwide? (required).</param>
        /// <param name="regionalScope">regionalScope.</param>
        /// <param name="subdivisions">List of subdivision references.</param>
        /// <param name="tags">Additional holday tags.</param>
        /// <param name="temporalScope">temporalScope.</param>
        /// <param name="type">type (required).</param>
        public HolidayByDateResponse(List<LocalizedText> comment = default(List<LocalizedText>), CountryReference country = default(CountryReference), List<GroupReference> groups = default(List<GroupReference>), Guid? id = default(Guid?), List<LocalizedText> name = default(List<LocalizedText>), bool? nationwide = default(bool?), RegionalScope regionalScope = default(RegionalScope), List<SubdivisionReference> subdivisions = default(List<SubdivisionReference>), List<string> tags = default(List<string>), TemporalScope temporalScope = default(TemporalScope), HolidayType type = default(HolidayType))
        {
            // to ensure "country" is required (not null)
            if (country == null)
            {
                throw new InvalidDataException("country is a required property for HolidayByDateResponse and cannot be null");
            }
            else
            {
                this.Country = country;
            }
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new InvalidDataException("id is a required property for HolidayByDateResponse and cannot be null");
            }
            else
            {
                this.Id = id;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for HolidayByDateResponse and cannot be null");
            }
            else
            {
                this.Name = name;
            }
            // to ensure "nationwide" is required (not null)
            if (nationwide == null)
            {
                throw new InvalidDataException("nationwide is a required property for HolidayByDateResponse and cannot be null");
            }
            else
            {
                this.Nationwide = nationwide;
            }
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for HolidayByDateResponse and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            this.Comment = comment;
            this.Groups = groups;
            this.RegionalScope = regionalScope;
            this.Subdivisions = subdivisions;
            this.Tags = tags;
            this.TemporalScope = temporalScope;
        }
        
        /// <summary>
        /// Additional localized comments
        /// </summary>
        /// <value>Additional localized comments</value>
        [DataMember(Name="comment", EmitDefaultValue=false)]
        public List<LocalizedText> Comment { get; set; }

        /// <summary>
        /// Gets or Sets Country
        /// </summary>
        [DataMember(Name="country", EmitDefaultValue=false)]
        public CountryReference Country { get; set; }

        /// <summary>
        /// List of group references
        /// </summary>
        /// <value>List of group references</value>
        [DataMember(Name="groups", EmitDefaultValue=false)]
        public List<GroupReference> Groups { get; set; }

        /// <summary>
        /// Unique holiday id
        /// </summary>
        /// <value>Unique holiday id</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public Guid? Id { get; set; }

        /// <summary>
        /// Localized names of the holiday
        /// </summary>
        /// <value>Localized names of the holiday</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public List<LocalizedText> Name { get; set; }

        /// <summary>
        /// Is the holiday nationwide?
        /// </summary>
        /// <value>Is the holiday nationwide?</value>
        [DataMember(Name="nationwide", EmitDefaultValue=false)]
        public bool? Nationwide { get; set; }

        /// <summary>
        /// Gets or Sets RegionalScope
        /// </summary>
        [DataMember(Name="regionalScope", EmitDefaultValue=false)]
        public RegionalScope RegionalScope { get; set; }

        /// <summary>
        /// List of subdivision references
        /// </summary>
        /// <value>List of subdivision references</value>
        [DataMember(Name="subdivisions", EmitDefaultValue=false)]
        public List<SubdivisionReference> Subdivisions { get; set; }

        /// <summary>
        /// Additional holday tags
        /// </summary>
        /// <value>Additional holday tags</value>
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets TemporalScope
        /// </summary>
        [DataMember(Name="temporalScope", EmitDefaultValue=false)]
        public TemporalScope TemporalScope { get; set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public HolidayType Type { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class HolidayByDateResponse {\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  Country: ").Append(Country).Append("\n");
            sb.Append("  Groups: ").Append(Groups).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Nationwide: ").Append(Nationwide).Append("\n");
            sb.Append("  RegionalScope: ").Append(RegionalScope).Append("\n");
            sb.Append("  Subdivisions: ").Append(Subdivisions).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  TemporalScope: ").Append(TemporalScope).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as HolidayByDateResponse);
        }

        /// <summary>
        /// Returns true if HolidayByDateResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of HolidayByDateResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(HolidayByDateResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Comment == input.Comment ||
                    this.Comment != null &&
                    input.Comment != null &&
                    this.Comment.SequenceEqual(input.Comment)
                ) && 
                (
                    this.Country == input.Country ||
                    (this.Country != null &&
                    this.Country.Equals(input.Country))
                ) && 
                (
                    this.Groups == input.Groups ||
                    this.Groups != null &&
                    input.Groups != null &&
                    this.Groups.SequenceEqual(input.Groups)
                ) && 
                (
                    this.Id == input.Id ||
                    (this.Id != null &&
                    this.Id.Equals(input.Id))
                ) && 
                (
                    this.Name == input.Name ||
                    this.Name != null &&
                    input.Name != null &&
                    this.Name.SequenceEqual(input.Name)
                ) && 
                (
                    this.Nationwide == input.Nationwide ||
                    (this.Nationwide != null &&
                    this.Nationwide.Equals(input.Nationwide))
                ) && 
                (
                    this.RegionalScope == input.RegionalScope ||
                    (this.RegionalScope != null &&
                    this.RegionalScope.Equals(input.RegionalScope))
                ) && 
                (
                    this.Subdivisions == input.Subdivisions ||
                    this.Subdivisions != null &&
                    input.Subdivisions != null &&
                    this.Subdivisions.SequenceEqual(input.Subdivisions)
                ) && 
                (
                    this.Tags == input.Tags ||
                    this.Tags != null &&
                    input.Tags != null &&
                    this.Tags.SequenceEqual(input.Tags)
                ) && 
                (
                    this.TemporalScope == input.TemporalScope ||
                    (this.TemporalScope != null &&
                    this.TemporalScope.Equals(input.TemporalScope))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Comment != null)
                    hashCode = hashCode * 59 + this.Comment.GetHashCode();
                if (this.Country != null)
                    hashCode = hashCode * 59 + this.Country.GetHashCode();
                if (this.Groups != null)
                    hashCode = hashCode * 59 + this.Groups.GetHashCode();
                if (this.Id != null)
                    hashCode = hashCode * 59 + this.Id.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                if (this.Nationwide != null)
                    hashCode = hashCode * 59 + this.Nationwide.GetHashCode();
                if (this.RegionalScope != null)
                    hashCode = hashCode * 59 + this.RegionalScope.GetHashCode();
                if (this.Subdivisions != null)
                    hashCode = hashCode * 59 + this.Subdivisions.GetHashCode();
                if (this.Tags != null)
                    hashCode = hashCode * 59 + this.Tags.GetHashCode();
                if (this.TemporalScope != null)
                    hashCode = hashCode * 59 + this.TemporalScope.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
