/* 
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using Newtonsoft.Json;

namespace OpenHolidaysApi.Model
{
    /// <summary>
    /// Representation of a language as defined in ISO-639-1
    /// </summary>
    [DataContract]
        public partial class LanguageResponse :  IEquatable<LanguageResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageResponse" /> class.
        /// </summary>
        /// <param name="isoCode">ISO-639-1 language code (required).</param>
        /// <param name="name">Localized language names (required).</param>
        public LanguageResponse(string isoCode = default(string), List<LocalizedText> name = default(List<LocalizedText>))
        {
            // to ensure "isoCode" is required (not null)
            if (isoCode == null)
            {
                throw new InvalidDataException("isoCode is a required property for LanguageResponse and cannot be null");
            }
            else
            {
                this.IsoCode = isoCode;
            }
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new InvalidDataException("name is a required property for LanguageResponse and cannot be null");
            }
            else
            {
                this.Name = name;
            }
        }
        
        /// <summary>
        /// ISO-639-1 language code
        /// </summary>
        /// <value>ISO-639-1 language code</value>
        [DataMember(Name="isoCode", EmitDefaultValue=false)]
        public string IsoCode { get; set; }

        /// <summary>
        /// Localized language names
        /// </summary>
        /// <value>Localized language names</value>
        [DataMember(Name="name", EmitDefaultValue=false)]
        public List<LocalizedText> Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class LanguageResponse {\n");
            sb.Append("  IsoCode: ").Append(IsoCode).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LanguageResponse);
        }

        /// <summary>
        /// Returns true if LanguageResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of LanguageResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LanguageResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IsoCode == input.IsoCode ||
                    (this.IsoCode != null &&
                    this.IsoCode.Equals(input.IsoCode))
                ) && 
                (
                    this.Name == input.Name ||
                    this.Name != null &&
                    input.Name != null &&
                    this.Name.SequenceEqual(input.Name)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IsoCode != null)
                    hashCode = hashCode * 59 + this.IsoCode.GetHashCode();
                if (this.Name != null)
                    hashCode = hashCode * 59 + this.Name.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
