/*
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * OpenAPI spec version: v1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace OpenHolidaysApi.Model;

/// <summary>
///     Regional scope of a holdiay
/// </summary>
/// <value>Regional scope of a holdiay</value>
[JsonConverter(typeof(StringEnumConverter))]
public enum RegionalScope
{
    /// <summary>
    ///     Enum National for value: National
    /// </summary>
    [EnumMember(Value = "National")] National = 1,

    /// <summary>
    ///     Enum Regional for value: Regional
    /// </summary>
    [EnumMember(Value = "Regional")] Regional = 2,

    /// <summary>
    ///     Enum Local for value: Local
    /// </summary>
    [EnumMember(Value = "Local")] Local = 3
}