/* 
 * OpenHolidays API v1
 *
 * Open Data API for public and school holidays
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace OpenHolidaysApi.Model
{
    /// <summary>
    /// Temporal scope of a holdiay
    /// </summary>
    /// <value>Temporal scope of a holdiay</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum TemporalScope
    {
        /// <summary>
        /// Enum FullDay for value: FullDay
        /// </summary>
        [EnumMember(Value = "FullDay")]
        FullDay = 1,
        /// <summary>
        /// Enum HalfDay for value: HalfDay
        /// </summary>
        [EnumMember(Value = "HalfDay")]
        HalfDay = 2    }
}
